[dev]sorted pics to the top
raft-tech/raft-tech.github.io pull request #193
Opened 2020-10-22 17:22 UTC by MissyM2

#### Change
made edits to *about.html* to sort the members with sketches to the top of the page.

#### Testing

- no new errors on the console
- looks visually correct
<img width="250" alt="Screen Shot 2020-10-22 at 1 22 14 PM" src="https://user-images.githubusercontent.com/34319929/96907721-9fcbfe80-1469-11eb-94f7-5b5eb679a798.png">

2020-10-22 22:00 UTC, meissadia requested changes

2020-10-22 22:00 UTC, meissadia commented on _layouts/about.html
> +    <ul id="members">
Also, element IDs are supposed to be unique, so can you please switch from `<ul id="members">` to `<ul class="members">` for both occurrences and update the CSS accordingly?

2020-10-22 22:58 UTC, MissyM2 commented on _layouts/about.html
> +    <ul id="members">
I made your updates and I added 'margin-bottom:0' on the ul to get rid of the little bit of extra space.

2020-10-23 18:55 UTC, meissadia commented on _layouts/about.html
> +    <ul id="members">
@MissyM2 I usually resolve the convo once it no longer requires a response.

2020-10-23 19:05 UTC, meissadia approved these changes
🚀

2020-10-23 19:05 UTC, merged