Agile is About Your Turning Radius Blog Post
raft-tech/raft-tech.github.io pull request #352
Opened 2022-01-21 02:22 UTC by apmarshall

2022-01-24 19:33 UTC, BarakStout commented on _posts/2022-07-02-Agile-Is-About-Measuring-Your-Turning-Radius.md
> +short_title: "The Real Meaning of Agile"
Please remove "Real"

2022-01-24 21:56 UTC, apmarshall commented on _posts/2022-07-02-Agile-Is-About-Measuring-Your-Turning-Radius.md
> +Everyone these days wants to be "agile". Where "agile" is a synonym for "nimble", and being nimble is about how fast you can change directions, not how fast you can move in a straight line. Think abo
```suggestion
Everyone these days wants to be "agile", but "agile" is a synonym for "nimble", and being nimble is about how fast you can change directions, not how fast you can move in a straight line. Think about a basketball player who can react quickly to where the defense is setting up and find just the right angle for their pass or shot. That’s what it means to be nimble.
```

2022-02-02 18:35 UTC, BarakStout requested changes

2022-02-02 18:35 UTC, BarakStout commented on _posts/2022-07-02-Agile-Is-About-Measuring-Your-Turning-Radius.md
> +date: 2022-01-07
Needs to update date.

2022-02-08 15:22 UTC, apmarshall commented
@BarakStout I believe this is ready for merging. Let me know if there is anything else required.

2022-02-08 15:23 UTC, BarakStout approved these changes
LGTM 👍

2022-02-08 15:28 UTC, merged